#!/bin/bash -xe

export PATH=$PATH:/usr/local/bin

AWS=$(which aws)
echo export "SOCA_BASE_OS=rhel7" >> /etc/environment
echo export "SOCA_CONFIGURATION=soca-geoeast" >> /etc/environment
echo export "AWS_DEFAULT_REGION=cn-northwest-1" >> /etc/environment
echo export "SOCA_INSTALL_BUCKET=nwcd-solutions" >> /etc/environment
echo export "SOCA_INSTALL_BUCKET_FOLDER=scale-out-computing-on-aws/v2.6.0" >> /etc/environment
echo export "SOCA_PATCH_BUCKET=nwcd-solutions" >> /etc/environment
echo export "SOCA_PATCH_BUCKET_FOLDER=soca/v2.6.0" >> /etc/environment
echo export "SOCA_VERSION=2.6.0" >> /etc/environment
echo export "SOCA_INSTALL_AMI=ami-07f71407ad8751767" >> /etc/environment
echo export "DCV_USERNAME=admin">> /etc/environment
echo export "DCV_USER_PASSWD=NWcd@1234" >> /etc/environment
source /etc/environment

AWS=$(which aws)
echo "@reboot /bin/bash /root/SchedulerPostReboot.sh soca-china-deployment scale-out-computing-on-aws/v2.6.0 admin 'NWcd@1234' nwcd-samples soca/v2.6.4.1 >> /root/PostRebootConfig.log 2>&1" | crontab -

/bin/bash /root/Scheduler.sh >> /root/Scheduler.sh.log 2>&1


/apps/soca/soca-geoeast/python/latest/bin/python3  /apps/soca/soca-geoeast/cluster_manager/add_nodes.py      --instance_type=c5.large      --desired_capacity=1      --keep_forever true      --job_owner mickael      --job_name always_on_capacity      --queue alwayson --instance_ami=ami-07f71407ad8751767 --root_size=100

sudo /apps/soca/$SOCA_CONFIGURATION/python/latest/bin/python3  /apps/soca/$SOCA_CONFIGURATION/cluster_manager/add_cluster.py      --instance_type=c5.large      --desired_capacity=1      --keep_forever true      --job_owner mickael      --job_name always_on_capacity      --queue alwayson --instance_ami=ami-07f71407ad8751767 --root_size=100